import { registerEnumType } from '@nestjs/graphql';

export enum ActivityType {
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_MEMBER_ADDED = 'WORKSPACE_MEMBER_ADDED',
  WORKSPACE_MEMBER_REMOVED = 'WORKSPACE_MEMBER_REMOVED',
  WORKSPACE_MEMBER_LEFT = 'WORKSPACE_MEMBER_LEFT',
  BOARD_CREATED = 'BOARD_CREATED',
  BOARD_UPDATED = 'BOARD_UPDATED',
  LIST_CREATED = 'LIST_CREATED',
  LIST_UPDATED = 'LIST_UPDATED',
  LIST_ARCHIVED = 'LIST_ARCHIVED',
  LIST_REORDERED = 'LIST_REORDERED',
  CARD_CREATED = 'CARD_CREATED',
  CARD_UPDATED = 'CARD_UPDATED',
  CARD_ARCHIVED = 'CARD_ARCHIVED',
  CARD_DELETED = 'CARD_DELETED',
  CARD_MOVED = 'CARD_MOVED',
  CARD_DUE_DATE_SET = 'CARD_DUE_DATE_SET',
  CARD_DUE_DATE_CLEARED = 'CARD_DUE_DATE_CLEARED',
  CARD_DONE_SET = 'CARD_DONE_SET',
  CARD_LABEL_ADDED = 'CARD_LABEL_ADDED',
  CARD_LABEL_REMOVED = 'CARD_LABEL_REMOVED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  COMMENT_DELETED = 'COMMENT_DELETED',
  LABEL_CREATED = 'LABEL_CREATED',
  LABEL_UPDATED = 'LABEL_UPDATED',
  LABEL_DELETED = 'LABEL_DELETED',
}

registerEnumType(ActivityType, {
  name: 'ActivityType',
});

